# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\x12\x04user\x1a\x1bgoogle/protobuf/empty.proto\"l\n\x04User\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08username\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x12\n\nfirst_name\x18\x04 \x01(\t\x12\x11\n\tlast_name\x18\x05 \x01(\t\x12\x10\n\x08password\x18\x06 \x01(\t\"\x11\n\x0fUserListRequest\"!\n\x13UserRetrieveRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x32\xed\x01\n\x0eUserController\x12-\n\x04List\x12\x15.user.UserListRequest\x1a\n.user.User\"\x00\x30\x01\x12\"\n\x06\x43reate\x12\n.user.User\x1a\n.user.User\"\x00\x12\x33\n\x08Retrieve\x12\x19.user.UserRetrieveRequest\x1a\n.user.User\"\x00\x12\"\n\x06Update\x12\n.user.User\x1a\n.user.User\"\x00\x12/\n\x07\x44\x65stroy\x12\n.user.User\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3')



_USER = DESCRIPTOR.message_types_by_name['User']
_USERLISTREQUEST = DESCRIPTOR.message_types_by_name['UserListRequest']
_USERRETRIEVEREQUEST = DESCRIPTOR.message_types_by_name['UserRetrieveRequest']
User = _reflection.GeneratedProtocolMessageType('User', (_message.Message,), {
  'DESCRIPTOR' : _USER,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:user.User)
  })
_sym_db.RegisterMessage(User)

UserListRequest = _reflection.GeneratedProtocolMessageType('UserListRequest', (_message.Message,), {
  'DESCRIPTOR' : _USERLISTREQUEST,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:user.UserListRequest)
  })
_sym_db.RegisterMessage(UserListRequest)

UserRetrieveRequest = _reflection.GeneratedProtocolMessageType('UserRetrieveRequest', (_message.Message,), {
  'DESCRIPTOR' : _USERRETRIEVEREQUEST,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:user.UserRetrieveRequest)
  })
_sym_db.RegisterMessage(UserRetrieveRequest)

_USERCONTROLLER = DESCRIPTOR.services_by_name['UserController']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _USER._serialized_start=49
  _USER._serialized_end=157
  _USERLISTREQUEST._serialized_start=159
  _USERLISTREQUEST._serialized_end=176
  _USERRETRIEVEREQUEST._serialized_start=178
  _USERRETRIEVEREQUEST._serialized_end=211
  _USERCONTROLLER._serialized_start=214
  _USERCONTROLLER._serialized_end=451
# @@protoc_insertion_point(module_scope)
